import ContentSideNav from "../../components/global/ContentSideNav";


const PrivacyPolicy = (props) => {
  return (<div className="content-page d-md-grid">
    
    <aside className="d-none d-md-block">
      <h4 className="mb-2">On this page</h4>
      <ContentSideNav 
        targetIds={["info-Introduction", "info-Definitions", "info-Information-Collection-and-Use",
                  "info-Types-of-Data-We-Collect", "info-Use-of-Data", "info-Retention-of-Data", 
                  "info-Transfer-of-Data", "info-Disclosure-of-Data", "info-Security-of-Data", "info-Advertising", 
                  "info-Changes-to-this-Privacy-Policy", "info-Contact-Us"]}
      />
    </aside>

    <div className="info-div">

      <h1>Privacy Policy</h1>

      <div id="info-Introduction">
        <h2>Introduction</h2>
        <p>Welcome to <strong>Exampto.</strong></p>
        <p>Exampto  operates <strong>www.exampto.com</strong> </p>
        <p>Our Privacy Policy governs your visit to <strong>www.exampto.com</strong>, and explains how we collect, safeguard and 
            disclose information that results from your use of our Portal.</p>
        <p>We use your data to provide and improve Portal. By using Portal, you agree to the collection and use of 
            information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used 
            in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
        <p>Our Terms and Conditions <strong>(“Terms”)</strong> govern all use of our Portal and together with the Privacy Policy 
            constitutes your agreement with us <strong>(“agreement”)</strong>.</p>
      </div>

      <div id="info-Definitions">
        <h2>Definitions</h2>
        <p><strong>PORTAL</strong> means the www.exampto.com website operated by Exampto.</p>
        <p><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from 
          those and other information either in our possession or likely to come into our possession).</p>
        <p><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Portal or from Portal 
          infrastructure itself.</p>
        <p><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</p>
        <p><strong>THE USER</strong> is the individual using our Portal. The User corresponds to the Data Subject, who is the 
          subject of Personal Data.</p>
      </div>

      <div id="info-Information-Collection-and-Use">
        <h2>Information Collection and Use</h2>
        <p>We collect several different types of information for various purposes to provide and improve our Portal to you.</p>
      </div>

      <div id="info-Types-of-Data-We-Collect">
        <h2>Types of Data We Collect</h2>

        <h4>Personal Data</h4>
        <p>While using our Portal, we may ask you to provide us with certain personally identifiable information that 
            can be used to contact or identify you  Personally identifiable information may include, 
            but is not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City, Country</li>
          <li>Cookies and Usage Data</li>
        </ul>
        <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other 
            information that may be of interest to you. You may opt out of receiving any, or all, of these 
            communications from us by following the unsubscribe link.</p>

        <h4>Usage Data</h4>
        <p>We may also collect information that your browser sends whenever you visit our Portal or when you access 
            Portal by or through any device.</p>
        <p>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), 
            browser type, browser version, the pages of our Portal that you visit, the time and date of your visit, 
            the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p>When you access Portal with a device, this Usage Data may include information such as the type of 
            device you use, your device unique ID, the IP address of your device, your device operating system, 
            the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
        
        <h4>Location Data</h4>
        <p>We may use and store information about your location if you give us permission to do so. 
            We use this data to provide features of our Portal, to improve and customize our Portal.</p>
        <p>You can enable or disable location Portals when you use our Portal at any time by way of your device settings.</p>

        <h4>Tracking Cookies</h4>
        <p>We use cookies and similar tracking technologies to track the activity on our Portal and we hold certain 
            information.</p>
        <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. 
            Cookies are sent to your browser from a website and stored on your device. Other tracking technologies 
            are also used such as beacons, tags and scripts to collect and track information and to improve and 
            analyze our Portal.</p>
        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, 
            if you do not accept cookies, you may not be able to use some portions of our Portal.</p>

        <h4>Other Data</h4>
        <p>While using our Portal, we may also collect the following information: sex, age, date of birth, place 
            of birth,  citizenship, registration at place of residence and actual address.</p>

      </div>

      <div id="info-Use-of-Data">
        <h2>Use of Data</h2>
        <p>Exampto uses the collected data for the following purposes:</p>
        <ul>
          <li>to provide and maintain our Portal;</li>
          <li>to notify you about changes to our Portal;</li>
          <li>to allow you to participate in interactive features of our Portal when you choose to do so;</li>
          <li>to provide customer support;</li>
          <li>to gather analysis or valuable information so that we can improve our Portal;</li>
          <li>to monitor the usage of our Portal;</li>
          <li>to detect, prevent and address technical issues;</li>
          <li>to fulfil any other purpose for which you provide it;</li>
          <li>to carry out our obligations and enforce our rights arising from any contracts entered into between 
              you and us, including for billing and collection;</li>
          <li>to provide you with notices about your account or Contest, including expiration and renewal notices, 
              email-instructions, etc.;</li>
          <li>to provide you with news, special offers and general information about other goods, Portals and events 
              which we offer that are similar to those that you have already purchased or enquired about unless you have 
              opted not to receive such information;</li>
          <li>in any other way we may describe when you provide the information;</li>
          <li>for any other purpose with your consent.</li>
        </ul>
      </div>

      <div id="info-Retention-of-Data">
        <h2>Retention of Data</h2>
        <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this 
            Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our 
            legal obligations.</p>
        <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a 
            shorter period, except when this data is used to strengthen the security or to improve the functionality 
            of our Portal, or we are legally obligated to retain this data for longer time periods.</p>
      </div>

      <div id="info-Transfer-of-Data">
        <h2>Transfer of Data</h2>
        <p>Your information, including Personal Data, may be transferred to – and maintained on – computers 
            located outside of your state, province, country or other governmental jurisdiction where the data 
            protection laws may differ from those of your jurisdiction.</p>
        <p>If you are located outside India and choose to provide information to us, please note that we transfer 
            the data, including Personal Data, to India and process it there.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your 
            agreement to that transfer.</p>
        <p>Exampto will take all the steps reasonably necessary to ensure that your data is treated securely and 
            in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an 
            organisation or a country unless there are adequate controls in place including the security of your 
            data and other personal information.</p>
      </div>

      <div id="info-Disclosure-of-Data">
        <h2>Disclosure of Data</h2>
        <p>We may disclose personal information that we collect, or you provide:</p>
        <h4>Disclosure for Law Enforcement</h4>
        <p>Under certain circumstances, we may be required to disclose your personal information if required to do
            so by law or in response to valid request by public authorities.</p>
        <h4>Business Transactions</h4>
        <p>If we are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.</p>
        <h4>Other cases</h4>
        <p>We may disclose your information also:</p>
        <ul>
          <li>to our subsidiaries and affiliates;</li>
          <li>to contractors, Portal providers, and other third parties we use to support our business;</li>
          <li>to fulfill any legal requirement;</li>
          <li>to fulfill the purpose for which you provide it;</li>
          <li>for the purpose of including your company’s logo on our website;</li>
          <li>for any other purpose disclosed by us when you provide the information;</li>
          <li>with your consent in any other cases;</li>
          <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of 
              the Company, our customers, or others.</li>
        </ul>
      </div>

      <div id="info-Security-of-Data">
        <h2>Security of Data</h2>
        <p>The security of your data is important to us but remember that no method of transmission over the Internet 
            or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to 
            protect your Personal Data, we cannot guarantee its absolute security.</p>
        <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and 
            are obligated not to disclose or use it for any other purpose.</p>
      </div>

      <div id="info-Advertising">
        <h2>Advertising</h2>
        <p>We may use third-party Portal Providers to show advertisements to you to help support 
            and maintain our Portal.</p>
      </div>

      <div id="info-Changes-to-this-Privacy-Policy">
        <h2>Changes to this Privacy Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the 
            new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our Portal, prior to the change becoming 
            effective and update “effective date” at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy 
            Policy are effective when they are posted on this page.</p>
      </div>

      <div id="info-Contact-Us">
        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact us by emailing us at:
            <strong>Help@exampto.com</strong></p>
      </div>

    </div>

  </div>);
}

export default PrivacyPolicy;